### ISSUE TITLE
Crash with addressable 2.8.2

### ISSUE THREAD

**Issue by crevete** [lokalise/ruby-lokalise-api#27]
**Describe the bug**

When upgrading `addressable` gem to [2.8.2](https://github.com/sporkmonger/addressable/blob/main/CHANGELOG.md#addressable-282), the following snippet fails:
```ruby
require 'ruby_lokalise_api'
client = RubyLokaliseApi.client("<my_api_token>")
client.download_files("<my_project_id>", { ... })
```
The error message is: `NoMethodError: undefined method 'to_str' for :projects:Symbol` cf [this line](https://github.com/sporkmonger/addressable/blob/main/lib/addressable/template.rb#L900).

Please note that it works fine with `addressable` 2.8.1, and it does not hit that line (template.rb#L900).

**Workaround**

Fix the version of `addressable` to 2.8.1: 
```ruby
# Gemfile
gem 'addressable', "=2.8.1"`
```
**Your environment:**
 - OS : Ubuntu 22.04.2 LTS
 - Ruby version : 3.2.1

**Comment by bodrovis** [comment]
This is something not related to this gem, I believe. I would wait until this patch is merged and a new version is released https://github.com/sporkmonger/addressable/pull/499

**Comment by crevete** [comment]
Nice, thanks!

**Comment by bodrovis** [comment]
It runs fine with 2.8.3 so hopefully all should be good https://github.com/lokalise/ruby-lokalise-api/actions/runs/4612637293/jobs/8153765072
